version: '3'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: climate-shield-backend
    ports:
      - "12000:12000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/climateShield
    networks:
      - app-network

  frontend:
    build:
      context: ../front_hackthon
      dockerfile: ../Climate-Shield/frontend.Dockerfile
    container_name: climate-shield-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 